In [1]:
import torch

> Create a random tensor with shape (7, 7)

In [12]:
random_tensor = torch.rand(size = (7,7))
random_tensor

tensor([[0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])

>Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [16]:
random_tensor_2 = torch.rand(1,7)
tensor_3 = torch.mm(random_tensor, random_tensor_2.T)
tensor_3, tensor_3.shape

(tensor([[1.5331],
         [1.7889],
         [0.9251],
         [1.4775],
         [1.4008],
         [1.9364],
         [1.3134]]),
 torch.Size([7, 1]))

> Set the random seed to 0 and do exercises 2 & 3 over again

In [18]:
torch.manual_seed(0)
random_tensor_3 = torch.rand(size= (7,7))

torch.manual_seed(0)
random_tensor_4 = torch.rand(size= (1,7))

tensor_5 = torch.matmul(random_tensor_3, random_tensor_4.T)
tensor_5

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

> Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [23]:
cuda = torch.device('cuda')
with torch.cuda.device(0):
  torch.random.manual_seed(1234)
  gpu_random_tensor  = torch.rand(size = (2,2), device = cuda)

gpu_random_tensor.device

device(type='cuda', index=0)

> Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [24]:
random_tensor_6 = torch.rand(2,3)
random_tensor_7 = torch.rand(2,3)

In [25]:
random_tensor_6 = random_tensor_6.to(cuda)
random_tensor_7 = random_tensor_7.to(cuda)

random_tensor_6.device, random_tensor_7.device

(device(type='cuda', index=0), device(type='cuda', index=0))

> Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [26]:
tensor_8 = torch.mm(random_tensor_6, random_tensor_7.T)
tensor_8, tensor_8.device

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 device(type='cuda', index=0))

> Find the maximum and minimum values of the output of 7.

In [27]:
min_tensor_8 = tensor_8.min()
max_tensor_8 = tensor_8.max()

min_tensor_8, max_tensor_8

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

> Find the maximum and minimum index values of the output of 7.

In [28]:
min_tensor_8_position = tensor_8.argmin()
max_tensor_8_position = tensor_8.argmax()

min_tensor_8_position, max_tensor_8_position

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

> Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [32]:
with torch.cuda.device(0):
  torch.manual_seed(7)

  unsqueezed_tensor_9 = torch.rand(size = (1,1,1,10), device = cuda)
  squeezed_tensor_9 = unsqueezed_tensor_9.squeeze()

print(f'Unsqueezed_tensor: {unsqueezed_tensor_9}\n')
print(f'Unsqueezed_tensor shape: {unsqueezed_tensor_9.shape}\n')
print(f'Squeezed_tensor: {squeezed_tensor_9}\n')
print(f'Squeezed_tensor shape: {squeezed_tensor_9.shape}\n')

Unsqueezed_tensor: tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')

Unsqueezed_tensor shape: torch.Size([1, 1, 1, 10])

Squeezed_tensor: tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')

Squeezed_tensor shape: torch.Size([10])

