# Import Pytorch
`import torch`

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.0.1+cu118'

#Creating Tensors

## Scalers

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

## Vectors

In [6]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Can only be used on tensors
vector.item()

RuntimeError: ignored

## Matrix

In [10]:
matrix = torch.tensor([
    [7,8],
    [9,10]
])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

## Tensor

In [12]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
tensor.ndim, tensor.shape

(3, torch.Size([1, 3, 3]))

## Random Tensors

In [14]:
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.shape

(tensor([[0.0852, 0.8418, 0.8888, 0.0140],
         [0.8748, 0.4370, 0.9411, 0.7482],
         [0.7709, 0.9250, 0.7047, 0.2415]]),
 torch.Size([3, 4]))

In [15]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor, random_image_size_tensor.shape

(tensor([[[0.6351, 0.3481, 0.3422],
          [0.3695, 0.0456, 0.3902],
          [0.5767, 0.0377, 0.1230],
          ...,
          [0.4874, 0.7088, 0.5248],
          [0.3060, 0.2607, 0.5439],
          [0.3139, 0.6539, 0.4953]],
 
         [[0.4511, 0.3672, 0.8540],
          [0.7743, 0.5320, 0.8691],
          [0.4926, 0.9217, 0.2766],
          ...,
          [0.1653, 0.3860, 0.3380],
          [0.7885, 0.1874, 0.0734],
          [0.9486, 0.2909, 0.1584]],
 
         [[0.8609, 0.4429, 0.8218],
          [0.3289, 0.2397, 0.0066],
          [0.5616, 0.1506, 0.9227],
          ...,
          [0.9408, 0.7990, 0.6486],
          [0.0834, 0.9068, 0.7609],
          [0.3947, 0.8300, 0.9404]],
 
         ...,
 
         [[0.4570, 0.4938, 0.2446],
          [0.1306, 0.4920, 0.6476],
          [0.8933, 0.9698, 0.9257],
          ...,
          [0.5106, 0.1101, 0.5156],
          [0.1403, 0.7440, 0.3629],
          [0.5738, 0.3114, 0.8159]],
 
         [[0.3969, 0.4819, 0.3811],
          [0

## Zeros and Ones

In [16]:
zeros = torch.zeros(size = (3,4))
zeros, zeros.shape, zeros.ndim, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]),
 2,
 torch.float32)

In [17]:
ones = torch.ones(size = (3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

`torch.arange(start, end, step)`

- `start`: start of range
- `end`: end of range
- `step`: how many steps in between each values

In [18]:
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32,
                               device = None,
                               requires_grad = False)
float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3., 6. ,9.],
                               dtype = torch.half)

float_16_tensor.dtype

torch.float16

# Getting information from tensors

In [22]:
some_tensor = torch.rand(size = (3,4))

print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.9547, 0.1931, 0.4571, 0.7424],
        [0.3146, 0.4922, 0.4202, 0.1667],
        [0.1470, 0.1526, 0.2452, 0.1177]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating Tensors

## Basic Operations

1. Addition
2. Substraction
3. Multiplication (elemen-wise)
4. Division
5. Matrix Multiplication

In [33]:
# Addition
tensor = torch.tensor([1,2,4])
tensor+10

tensor([11, 12, 14])

In [34]:
# Multiplication
tensor * 10, torch.multiply(tensor, 10)

(tensor([10, 20, 40]), tensor([10, 20, 40]))

In [35]:
# Subtraction
tensor - 10

tensor([-9, -8, -6])

In [36]:
# Element-Wise multiplication
print(f'{tensor} * {tensor} = {tensor*tensor}')

tensor([1, 2, 4]) * tensor([1, 2, 4]) = tensor([ 1,  4, 16])


## Matrix Multiplication

- The no of columns of the `first matrix` must be the same as the no of rows of the `second matrix`

- The resulting matrix will have a shape of (`no of rows of the first matrix`, `no of columns of the second matrix`)

- `tensor1 @ tensor2` or `torch.matmul(tensor1, tensor2)`

In [37]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [38]:
# Element-wise operation
tensor * tensor

tensor([1, 4, 9])

In [39]:
# Matrix multiplication
torch.matmul(tensor, tensor), tensor @ tensor

(tensor(14), tensor(14))

In [40]:
%%time
# Matric Multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 131 µs, sys: 24 µs, total: 155 µs
Wall time: 159 µs


tensor(14)

In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 33.4 µs


tensor(14)

## Shape Errors

In [42]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype = torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [43]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [44]:
print(tensor_A)
print(tensor_B.T)
print(torch.transpose(tensor_B, 0, 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [45]:
print(f'Original Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n')
print(f'New Shapes: tensor_A: {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}\n')
print(f'Multipling: {tensor_A.shape} * {tensor_B.shape}\n')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput Shape: {output.shape}')

Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New Shapes: tensor_A: torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])

Multipling: torch.Size([3, 2]) * torch.Size([3, 2])

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output Shape: torch.Size([3, 3])


We can also use `torch.mm()` instead of `torch.matmul()`

In [46]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Example Linear Function Multiplication

In [47]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2, out_features = 6)
x = tensor_A
output = linear(x)
print(f'Input shape: {x.shape}\n')
print(f'Output:\n{output}\n\nOutput shape:{output.shape}')

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape:torch.Size([3, 6])


## Aggregation


In [48]:
X = torch.arange(0 ,100, 10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
print(f'Minimum: {X.min()}')
print(f'Maximum: {X.max()}')
print(f'Mean: {X.type(torch.float32).mean()}')
print(f'Sum: {X.sum()}')

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


- Can also use functions from torch

In [50]:
torch.max(X), torch.min(X), torch.mean(X.type(torch.float32)), torch.sum(X)

(tensor(90), tensor(0), tensor(45.), tensor(450))

## Positional Min/Max

- `torch.argmax()` to get the index of the max value

- `torch.argmin()` to get the index of the least value

In [51]:
tensor = torch.arange(10,100,10)
print(f'Tensor: {tensor}')
print(f'Index of the maximum value: {tensor.argmax()}')
print(f'Index of the least value: {tensor.argmin()}')

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index of the maximum value: 8
Index of the least value: 0


## Change Tensor Datatype

In [52]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [53]:
tensor_float16 = tensor.type(torch.half)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [54]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, staking, squeezing and unsqueezing

In [55]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [56]:
x_reshaped = x.reshape(shape = (1,7))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [57]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [58]:
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [59]:
x_stacked = torch.stack([x,x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [60]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [61]:
print(f'Previous tensor: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'\nNew Tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [62]:
x_original = torch.rand(size = (224,224, 3))

x_permuted = x_original.permute(2,0,1)

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

In [63]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
x[0][0]

tensor([1, 2, 3])

In [66]:
x[0][0][0]

tensor(1)

In [67]:
x[:, 0]

tensor([[1, 2, 3]])

In [68]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [69]:
x[:, 1, 1]

tensor([5])

In [70]:
x[0, 0, :]

tensor([1, 2, 3])

# Pytorch tensors and Numpy

> Numpy array to Tensor

In [71]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> Tensor to Numpy Array

In [73]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [74]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility
> Trying to take random out of random

In [75]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f'Tensor_A: {random_tensor_A}\n')
print(f'Tensor_B: {random_tensor_B}\n')
print(f'is Tensor_A equal to Tensor_B: \n {random_tensor_A == random_tensor_B}')


Tensor_A: tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor_B: tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

is Tensor_A equal to Tensor_B: 
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


> Let's make them the same

In [76]:
random_seed = 42
torch.manual_seed(seed = random_seed)
random_tensor_C =  torch.rand(3,4)

torch.random.manual_seed(seed = random_seed)
# torch.manual_seed(seed = random_seed) also works

random_tensor_D = torch.rand(3,4)

print(f'Tensor_C: {random_tensor_C}\n')
print(f'Tensor_D: {random_tensor_D}\n')
print(f'is Tensor_C equal to Tensor_D: \n {random_tensor_C == random_tensor_D}')


Tensor_C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor_D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

is Tensor_C equal to Tensor_D: 
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running Tensors on GPUS

In [77]:
torch.cuda.is_available()

True

In [79]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [80]:
torch.cuda.device_count()

1

## Moving tensors to a GPU

In [81]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU

In [82]:
tensor_on_gpu.numpy()

TypeError: ignored

In [83]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [84]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')